# directories below are saved under this directory. Change to sejun!
SUB_DIR: ../../data/volume/seungjae

# START FROM HERE
PREPROCESSED_DIR: 'preprocessed_512_512'
#PREPROCESSED_TEST_DIR: 'preprocessed_test_256_256'
TRAIN_DF: 'train_512_512.csv'
FOLD_DF: '6fold_0.csv'
CHECKPOINT_DIR: 'checkpoints/base_512'
LOG_DIR: 'seungjae_512'

####################################
MEMO: 'base'
####################################

PREPROCESS: True
EDA: False

N_SPLITS: 6
N_FOLD: 0
SAMPLER: ''
LABEL_SMOOTHING: 0

PARALLEL: False
DEBUG: False
PRINT_EVERY: 10

TRAIN:
  NUM_EPOCHS: 100
  BATCH_SIZE: 16
  NUM_WORKERS: 4

EVAL:
  BATCH_SIZE: 32
  NUM_WORKERS: 4

DATA:
  IMG_H: 512
  IMG_W: 512

MODEL:
  ARCHITECTURE: 'Unet'
  ENCODER: 'resnet18'
  IN_CHANNELS: 3

LOSS:
  NAME: 'bce_dice'
  FINETUNE_EPOCH: 100
  FINETUNE_LOSS: 'binary_lovasz_loss'

OPTIMIZER:
  NAME: 'radam'
  LR: 0.001
  PARAMS:

SCHEDULER:
  NAME: 'multi_step'
  PARAMS:
    milestones: [10,50]
    gamma: 0.1
