# DO NOT FIX
TRAIN_DIR: '../../data/train'
TEST_DIR: '../../data/test'
OUTPUT_DIR: '../../data/output'
VOLUME_DIR: '../../data/volume'

# directories below are saved under this directory. Change to sejun!
SUB_DIR: ../../data/volume/seungjae

# START FROM HERE
PREPROCESSED_DIR: 'preprocessed_256_256'
PREPROCESSED_TEST_DIR: 'preprocessed_test_256_256'
TRAIN_DF: 'train_256_256.csv'
FOLD_DF: '6fold_0.csv'
CHECKPOINT_DIR: 'checkpoints/base'

LOG_DIR: 'seungjae_base'

####################################
MEMO: 'base'
####################################

PREPROCESS: False
EDA: False

N_SPLITS: 6
N_FOLD: 0
SAMPLER: ''
LABEL_SMOOTHING: 0

PARALLEL: False
DEBUG: False
PRINT_EVERY: 10

TRAIN:
  NUM_EPOCHS: 10
  BATCH_SIZE: 16
  NUM_WORKERS: 4

EVAL:
  BATCH_SIZE: 32
  NUM_WORKERS: 4

DATA:
  IMG_H: 256
  IMG_W: 256

MODEL:
  ARCHITECTURE: 'Unet'
  ENCODER: 'resnet18'
  IN_CHANNELS: 3

LOSS:
  NAME: 'binary_lovasz_loss'
  FINETUNE_EPOCH: 5
  FINETUNE_LOSS: 'binary_lovasz_loss'

OPTIMIZER:
  NAME: 'radam'
  LR: 0.001
  PARAMS:

SCHEDULER:
  NAME: 'multi_step'
  PARAMS:
    milestones: [5]
    gamma: 0.1
